spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiameds
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 'create' for development; 'update' or 'none' for production
    show-sql: true  # Optional: Shows SQL queries in logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 10  # Batch size for collection loading

  server:
    port: 8080  # Port on which the application runs

  security:
    user:
      name: user  # Default user (for basic auth, if used)
      password: password  # Default password

# Swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /doc  # Swagger UI path

# Logging configuration
logging:
  level:
    org.springframework: INFO  # General logging level
    org.springframework.security: DEBUG  # Detailed logging for Spring Security (optional)
    com:
      fasterxml:
        jackson: DEBUG  # Enable detailed logging for Jackson (Deserialization issues)
